# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk11

# Improve Build Speed https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2

# Notifications https://docs.travis-ci.com/user/notifications/
#notifications:
#  email:
#    recipients:
#      - y.dubovitsky@gmail.com
#    on_success: always # default: change
#    on_failure: always # default: always